version: "3.0"
services:
  dbpedia-lookup-search:
     build: .
     restart: always
     ports:
          - 9273:8080
     volumes:
                - ${APP_PATH}/${APP_NAME}/app-config.yml:/root/app-config.yml
                - ${APP_PATH}/template.xsl:/root/template.xsl
                - ${APP_PATH}/${APP_NAME}/index:/root/index/
                - ${APP_PATH}/last_data/:/root/data
                - ${APP_PATH}/${APP_NAME}/tdb:/root/tdb 
